// Expo config plugin: let the Android app trust user-installed CA certificates.
//
// Android apps trust ONLY the system CA store and, since Android 7 (API 24),
// ignore CAs the user installed themselves — unlike Chrome, which honors them.
// SUB/WAVE's audience is self-hosted/homelab, where stations commonly sit behind
// a private/internal CA. The browser on the phone trusts that station (the user
// installed the CA), but the app rejects it with:
//
//   javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException:
//   Trust anchor for certification path not found.
//
// (issue #458). This plugin emits a network-security-config that adds `user` to
// the trust anchors alongside `system`, so the app behaves like the browser: if
// the user installed their CA on the device, the app trusts it too. Publicly
// trusted certs (Let's Encrypt, etc.) keep working via `system`.
//
// IMPORTANT: once a networkSecurityConfig is present, Android (API >=24) IGNORES
// the manifest `android:usesCleartextTraffic` attribute and governs cleartext
// from this file instead. So `cleartextTrafficPermitted="true"` MUST stay here,
// or we'd silently break the HTTP/LAN-station support added in #464.
//
// android/ is regenerated by `expo prebuild` (CNG, gitignored), so this can't be
// a checked-in file — the plugin writes it on every prebuild and points the
// manifest at it. Mirrors plugins/withGradleVersion.js.
//
// Usage in app.json plugins: "./plugins/withAndroidUserCaTrust"

const { withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidUserCaTrust.js — do not edit by hand. -->
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" />
        </trust-anchors>
    </base-config>
</network-security-config>
`;

// Write res/xml/network_security_config.xml into the prebuilt android project.
function withNetworkSecurityConfigFile(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const xmlDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, 'network_security_config.xml'), XML);
      return cfg;
    },
  ]);
}

// Point <application> at the config above.
function withNetworkSecurityConfigManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = cfg.modResults.manifest.application?.[0];
    if (!app) {
      throw new Error('[withAndroidUserCaTrust] <application> not found in AndroidManifest.xml');
    }
    app.$['android:networkSecurityConfig'] = '@xml/network_security_config';
    return cfg;
  });
}

module.exports = function withAndroidUserCaTrust(config) {
  return withNetworkSecurityConfigManifest(withNetworkSecurityConfigFile(config));
};
