// Expo config plugin: the native CarPlay wiring for react-native-carplay.
//
// CarPlay template apps require the UIScene lifecycle: Info.plist declares a
// scene manifest with a CarPlay scene role and a phone scene role, and each
// role names a delegate class. This plugin generates everything on prebuild
// (ios/ is CNG, gitignored):
//
//   1. `com.apple.developer.carplay-audio` in the entitlements — Apple-granted
//      "additional capability". Simulator builds ignore provisioning, so this
//      is what makes the CarPlay Simulator show the app during development.
//      DEVICE builds fail codesigning until Apple grants the entitlement AND
//      it's enabled on the App ID (developer portal → Additional Capabilities
//      → regenerate profiles; EAS cannot sync it automatically). Until then,
//      device build profiles set SUBWAVE_NO_CARPLAY_ENTITLEMENT=1 in eas.json
//      to strip the key — delete those lines once the grant lands.
//   2. UIApplicationSceneManifest in Info.plist (CarPlay + phone roles).
//   3. CarSceneDelegate.swift / PhoneSceneDelegate.swift next to the generated
//      AppDelegate, registered in the Xcode project. The phone delegate
//      re-parents the AppDelegate's React rootViewController into the scene
//      window (the app's UI is otherwise unchanged), and forwards deep links —
//      under the scene lifecycle iOS delivers URLs to the scene, not to
//      AppDelegate's open-url handler (expo-router/dev-client rely on them).
//
// The delegate pattern follows Jellify (react-native-carplay + RN 0.86 + New
// Arch in production): https://github.com/anultravioletaurora/Jellify — the
// scene split itself needs no AppDelegate changes because the static manifest
// names the delegate classes.
//
// SDK-upgrade caveat (see app/CLAUDE.md): whenever Expo bumps its AppDelegate
// template, re-verify the PhoneSceneDelegate handoff (it assumes AppDelegate
// creates `window` and starts React Native in didFinishLaunching).
//
// Usage in app.json plugins: "./plugins/withCarPlay"

const {
  IOSConfig,
  withDangerousMod,
  withEntitlementsPlist,
  withInfoPlist,
  withXcodeProject,
} = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const ENTITLEMENT_KEY = 'com.apple.developer.carplay-audio';
const SWIFT_FILES = ['CarSceneDelegate.swift', 'PhoneSceneDelegate.swift'];

const CAR_SCENE_SWIFT = `// Generated by plugins/withCarPlay.js — do not edit by hand.
import CarPlay
import Foundation

class CarSceneDelegate: UIResponder, CPTemplateApplicationSceneDelegate {
  func templateApplicationScene(
    _ templateApplicationScene: CPTemplateApplicationScene,
    didConnect interfaceController: CPInterfaceController
  ) {
    RNCarPlay.connect(with: interfaceController, window: templateApplicationScene.carWindow)
  }

  func templateApplicationScene(
    _ templateApplicationScene: CPTemplateApplicationScene,
    didDisconnectInterfaceController interfaceController: CPInterfaceController
  ) {
    RNCarPlay.disconnect()
  }
}
`;

const PHONE_SCENE_SWIFT = `// Generated by plugins/withCarPlay.js — do not edit by hand.
import Foundation
import React
import UIKit

class PhoneSceneDelegate: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard let appDelegate = UIApplication.shared.delegate as? AppDelegate else { return }
    guard let windowScene = scene as? UIWindowScene else { return }

    // AppDelegate booted React Native into its own (never-shown) window in
    // didFinishLaunching — adopt that root view controller into the scene.
    let window = UIWindow(windowScene: windowScene)
    window.rootViewController = appDelegate.window?.rootViewController
    self.window = window
    window.makeKeyAndVisible()

    // Cold-start deep links arrive on the scene under the scene lifecycle.
    for context in connectionOptions.urlContexts {
      RCTLinkingManager.application(UIApplication.shared, open: context.url, options: [:])
    }
  }

  func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
    for context in URLContexts {
      RCTLinkingManager.application(UIApplication.shared, open: context.url, options: [:])
    }
  }

  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
    RCTLinkingManager.application(
      UIApplication.shared,
      continue: userActivity
    ) { _ in }
  }
}
`;

// 1. Entitlement (strippable while the Apple grant is pending — see header).
function withCarPlayEntitlement(config) {
  return withEntitlementsPlist(config, (cfg) => {
    if (process.env.SUBWAVE_NO_CARPLAY_ENTITLEMENT === '1') {
      delete cfg.modResults[ENTITLEMENT_KEY];
      return cfg;
    }
    cfg.modResults[ENTITLEMENT_KEY] = true;
    return cfg;
  });
}

// 2. Scene manifest. $(PRODUCT_MODULE_NAME) resolves to the app target's
// module, where the generated Swift classes live.
function withSceneManifest(config) {
  return withInfoPlist(config, (cfg) => {
    cfg.modResults.UIApplicationSceneManifest = {
      UIApplicationSupportsMultipleScenes: true,
      UISceneConfigurations: {
        CPTemplateApplicationSceneSessionRoleApplication: [
          {
            UISceneClassName: 'CPTemplateApplicationScene',
            UISceneConfigurationName: 'CarPlay',
            UISceneDelegateClassName: '$(PRODUCT_MODULE_NAME).CarSceneDelegate',
          },
        ],
        UIWindowSceneSessionRoleApplication: [
          {
            UISceneClassName: 'UIWindowScene',
            UISceneConfigurationName: 'Phone',
            UISceneDelegateClassName: '$(PRODUCT_MODULE_NAME).PhoneSceneDelegate',
          },
        ],
      },
    };
    return cfg;
  });
}

// 3a. Write the delegate sources + expose RNCarPlay to Swift via the bridging
// header. Dangerous mods run before withXcodeProject, so the files exist when
// step 3b registers them.
function withSceneDelegateFiles(config) {
  return withDangerousMod(config, [
    'ios',
    (cfg) => {
      const { platformProjectRoot, projectName } = cfg.modRequest;
      const targetDir = path.join(platformProjectRoot, projectName);
      fs.writeFileSync(path.join(targetDir, 'CarSceneDelegate.swift'), CAR_SCENE_SWIFT);
      fs.writeFileSync(path.join(targetDir, 'PhoneSceneDelegate.swift'), PHONE_SCENE_SWIFT);

      const header = path.join(targetDir, `${projectName}-Bridging-Header.h`);
      if (fs.existsSync(header)) {
        const current = fs.readFileSync(header, 'utf8');
        if (!current.includes('RNCarPlay.h')) {
          fs.writeFileSync(header, `${current.trimEnd()}\n#import "RNCarPlay.h"\n`);
        }
      } else {
        throw new Error(`[withCarPlay] bridging header not found at ${header}`);
      }
      return cfg;
    },
  ]);
}

// 3b. Register the sources with the app target.
function withSceneDelegateSources(config) {
  return withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const projectName = cfg.modRequest.projectName;
    for (const file of SWIFT_FILES) {
      const filepath = `${projectName}/${file}`;
      if (project.hasFile(filepath)) continue;
      IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
        filepath,
        groupName: projectName,
        project,
      });
    }
    return cfg;
  });
}

module.exports = function withCarPlay(config) {
  return withSceneDelegateSources(
    withSceneDelegateFiles(withSceneManifest(withCarPlayEntitlement(config))),
  );
};
