// Expo config plugin: declare the app to Android Auto.
//
// Android Auto only surfaces an app's media session if the app declares itself
// an Auto-compatible media app. react-native-track-player already contributes
// the MediaBrowserService (merged in from its own bundled manifest), so we only
// need the app-level declaration the library can't add for us:
//
//   1. res/xml/automotive_app_desc.xml  ->  <automotiveApp><uses name="media"/></automotiveApp>
//   2. <meta-data android:name="com.google.android.gms.car.application"
//                 android:resource="@xml/automotive_app_desc" /> in the manifest
//
// This is the minimum that makes Android Auto recognise SUB/WAVE and show the
// now-playing card while the stream is playing — it does NOT add a launchable
// in-car app icon (that needs a browse tree + Google review). iOS CarPlay
// now-playing needs no equivalent config (RNTP's MPNowPlayingInfoCenter wiring
// is enough), so this plugin is Android-only.
//
// android/ is gitignored and regenerated by `expo prebuild` (CNG), so these have
// to be injected at prebuild time rather than committed. Mirrors withGradleVersion.js.
//
// Usage in app.json plugins: "./plugins/withAndroidAuto"

const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const META_DATA_NAME = 'com.google.android.gms.car.application';
const AUTOMOTIVE_RESOURCE = '@xml/automotive_app_desc';
const AUTOMOTIVE_DESC_XML = `<automotiveApp>
    <uses name="media" />
</automotiveApp>
`;

// 1. Point the app at the automotive descriptor via an <application> meta-data.
//    addMetaDataItemToMainApplication is idempotent — it replaces any existing
//    item of the same name, so re-running prebuild won't duplicate the entry.
function withCarAppMetaData(config) {
  return withAndroidManifest(config, (cfg) => {
    const mainApplication = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    AndroidConfig.Manifest.addMetaDataItemToMainApplication(
      mainApplication,
      META_DATA_NAME,
      AUTOMOTIVE_RESOURCE,
      'resource',
    );
    return cfg;
  });
}

// 2. Write res/xml/automotive_app_desc.xml into the freshly-prebuilt tree.
function withAutomotiveDescXml(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const xmlDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, 'automotive_app_desc.xml'), AUTOMOTIVE_DESC_XML);
      return cfg;
    },
  ]);
}

module.exports = function withAndroidAuto(config) {
  config = withCarAppMetaData(config);
  config = withAutomotiveDescXml(config);
  return config;
};
