// Expo config plugin: declare the app to Android Auto as a media app.
//
// Android Auto only lists apps that (a) point a `com.google.android.gms.car.
// application` meta-data entry at an automotive descriptor declaring the
// `media` capability and (b) expose a browsable media service. The service
// half comes from our react-native-track-player fork (Media3
// MediaLibraryService — see src/car/browseTree.ts); this plugin supplies the
// manifest half. Without BOTH, the SUB/WAVE icon never appears on the car
// screen even though audio already plays over the car's Bluetooth session.
//
// Also adds the MEDIA_PLAY_FROM_SEARCH intent filter to the main activity so
// "Hey Google, play SUB/WAVE" resolves to us (car-app quality criterion VC-1;
// the query lands as Event.RemotePlaySearch in service.ts).
//
// ⚠ GOOGLE PLAY: builds carrying this declaration MUST NOT ship to Play.
// A previous manifest-only declaration (#444) was enforced against on
// 20 Jun 2026 — "Category not permitted — Media apps that use TTS engine
// readout for content are not permitted at this time" — and the build was
// pulled (#477). The AI DJ *is* TTS readout, so a compliant browse tree does
// not cure it. Play-bound profiles set SUBWAVE_NO_ANDROID_AUTO=1 in eas.json
// to strip the declaration (the JS browse tree stays; it's inert without the
// manifest). Dev/sideload/internal builds keep Android Auto working. Remove
// the env line only if Google's "at this time" policy changes or an appeal
// with the now-compliant MediaLibraryService implementation succeeds.
//
// android/ is regenerated by `expo prebuild` (CNG, gitignored), so this can't
// be a checked-in file — the plugin writes it on every prebuild. Mirrors
// plugins/withAndroidUserCaTrust.js.
//
// Usage in app.json plugins: "./plugins/withAndroidAuto"

const { withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidAuto.js — do not edit by hand. -->
<automotiveApp>
    <uses name="media"/>
</automotiveApp>
`;

// Write res/xml/automotive_app_desc.xml into the prebuilt android project.
function withAutomotiveDescFile(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const xmlDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, 'automotive_app_desc.xml'), XML);
      return cfg;
    },
  ]);
}

// <application>-level meta-data pointing at the descriptor, plus the voice
// search intent filter on the launcher activity.
function withCarManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = cfg.modResults.manifest.application?.[0];
    if (!app) {
      throw new Error('[withAndroidAuto] <application> not found in AndroidManifest.xml');
    }

    app['meta-data'] = app['meta-data'] || [];
    if (
      !app['meta-data'].some(
        (m) => m.$['android:name'] === 'com.google.android.gms.car.application',
      )
    ) {
      app['meta-data'].push({
        $: {
          'android:name': 'com.google.android.gms.car.application',
          'android:resource': '@xml/automotive_app_desc',
        },
      });
    }

    const mainActivity = (app.activity || []).find(
      (a) => a.$['android:name'] === '.MainActivity',
    );
    if (!mainActivity) {
      throw new Error('[withAndroidAuto] .MainActivity not found in AndroidManifest.xml');
    }
    mainActivity['intent-filter'] = mainActivity['intent-filter'] || [];
    const hasSearchFilter = mainActivity['intent-filter'].some((f) =>
      (f.action || []).some(
        (a) => a.$['android:name'] === 'android.media.action.MEDIA_PLAY_FROM_SEARCH',
      ),
    );
    if (!hasSearchFilter) {
      mainActivity['intent-filter'].push({
        action: [{ $: { 'android:name': 'android.media.action.MEDIA_PLAY_FROM_SEARCH' } }],
        category: [{ $: { 'android:name': 'android.intent.category.DEFAULT' } }],
      });
    }
    return cfg;
  });
}

module.exports = function withAndroidAuto(config) {
  if (process.env.SUBWAVE_NO_ANDROID_AUTO === '1') return config;
  return withCarManifest(withAutomotiveDescFile(config));
};
