// Subsonic auth, with real semantics: `t` must equal md5(password + s), and
// the legacy `p=` (plain or `enc:`-hex) is accepted too. The controller,
// Liquidsoap's subhttp downloads and the analyzer all present the same salt +
// token pair that a Navidrome would check.
//
// The credentials are the router's own (generated by the controller into
// config.json), never an operator's backend password.

import crypto from 'node:crypto';
import type { Request } from 'express';
import { credentials } from '../host/registry.js';

function q(req: Request, key: string): string | undefined {
  const v = (req.query as Record<string, unknown>)[key];
  if (typeof v === 'string') return v;
  if (Array.isArray(v) && typeof v[0] === 'string') return v[0];
  return undefined;
}

function safeEqual(a: string, b: string): boolean {
  const ab = Buffer.from(a);
  const bb = Buffer.from(b);
  return ab.length === bb.length && crypto.timingSafeEqual(ab, bb);
}

export function checkAuth(req: Request): { code: number; message: string } | null {
  const creds = credentials();
  if (!creds) return { code: 40, message: 'The music router has no credentials configured yet' };
  const u = q(req, 'u');
  if (!u) return { code: 10, message: "Required parameter 'u' is missing" };
  const t = q(req, 't');
  const s = q(req, 's');
  const p = q(req, 'p');
  let ok = false;
  if (safeEqual(u, creds.user)) {
    if (t && s) {
      ok = safeEqual(crypto.createHash('md5').update(creds.pass + s).digest('hex'), t.toLowerCase());
    } else if (p) {
      const plain = p.startsWith('enc:') ? Buffer.from(p.slice(4), 'hex').toString('utf8') : p;
      ok = safeEqual(plain, creds.pass);
    }
  }
  return ok ? null : { code: 40, message: 'Wrong username or password' };
}

/** HTTP Basic auth with the same credentials, for the controller's /internal calls. */
export function checkBasic(header: string | undefined): boolean {
  const creds = credentials();
  if (!creds || !header?.startsWith('Basic ')) return false;
  const decoded = Buffer.from(header.slice(6), 'base64').toString('utf8');
  const i = decoded.indexOf(':');
  if (i < 0) return false;
  return safeEqual(decoded.slice(0, i), creds.user) && safeEqual(decoded.slice(i + 1), creds.pass);
}
