// Generate cli/src/assets.generated.ts from the source compose files +
// .env.example at the repo root. Run this whenever those files change:
//
//   npm --prefix cli run embed-assets
//
// The generated file is committed so contributors don't need to run this
// before `tsx src/cli.ts`. CI verifies the embedded copy matches the source
// to catch staleness (see .github/workflows/cli-assets-check.yml).
//
// Why embed: a Bun-compiled `subwave` binary has no access to the repo's
// docker-compose.yml at runtime. `subwave init` materialises the embedded
// strings into the operator's chosen SUBWAVE_HOME directory.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '..', '..');
const OUT_FILE = resolve(HERE, '..', 'src', 'assets.generated.ts');

interface Asset {
  // Constant name in assets.generated.ts (uppercase snake).
  name: string;
  // Relative path from the repo root.
  source: string;
}

const ASSETS: Asset[] = [
  { name: 'COMPOSE_YML',                source: 'docker-compose.yml' },
  { name: 'COMPOSE_BYO_YML',            source: 'docker-compose.byo.yml' },
  { name: 'COMPOSE_DEV_YML',            source: 'docker-compose.dev.yml' },
  { name: 'COMPOSE_TTS_HEAVY_GPU_YML',  source: 'docker-compose.tts-heavy-gpu.yml' },
  { name: 'ENV_EXAMPLE',                source: '.env.example' },
];

const banner = `// AUTO-GENERATED by cli/scripts/embed-assets.ts — do not edit by hand.
// Regenerate with: npm --prefix cli run embed-assets
//
// These string constants are the source-of-truth content that
// \`subwave init\` materialises into SUBWAVE_HOME. CI verifies they match
// the original files at the repo root.
`;

function encode(content: string): string {
  // Backtick-quoted template string with the minimum escape set required to
  // round-trip exactly: backslash, backtick, and \${ (template interpolation
  // start). Newlines are preserved literally — they render cleaner in the
  // generated file than `\n` escapes.
  return content
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

function main(): void {
  const parts: string[] = [banner, ''];
  for (const a of ASSETS) {
    const abs = resolve(REPO_ROOT, a.source);
    const body = readFileSync(abs, 'utf8');
    parts.push(`// ${a.source}`);
    parts.push(`export const ${a.name} = \`${encode(body)}\`;`);
    parts.push('');
  }
  // Embed cli/package.json's version. The runtime readFileSync trick in
  // cli.ts doesn't survive `bun build --compile` (the bundled binary has no
  // package.json at runtime), so `--version` previously printed "unknown".
  // Bake the string in at embed time — release-please bumps this in lockstep
  // with the git tag, so the embedded version always matches the release the
  // binary came from.
  //
  // The trailing `x-release-please-version` marker lets release-please bump
  // this line itself during the release PR (this file is a `generic`
  // extra-file in release-please-config.json). Without it the committed copy
  // would lag the version bump in cli/package.json until someone re-ran this
  // script, and the verify-cli-assets check would fail on the next PR. Keep
  // the marker on the same line as the version.
  const pkg = JSON.parse(readFileSync(resolve(REPO_ROOT, 'cli', 'package.json'), 'utf8')) as { version: string };
  parts.push('// cli/package.json#version (embedded so the compiled binary can self-identify');
  parts.push('// — used by `subwave --version`).');
  parts.push(`export const CLI_VERSION = \`${encode(pkg.version)}\`; // x-release-please-version`);
  parts.push('');

  writeFileSync(OUT_FILE, parts.join('\n'));
  const sizes = ASSETS.map((a) => {
    const abs = resolve(REPO_ROOT, a.source);
    return `${a.source} (${readFileSync(abs, 'utf8').length} bytes)`;
  });
  process.stdout.write(`embedded ${ASSETS.length} files + CLI_VERSION=${pkg.version} → ${OUT_FILE}\n`);
  for (const s of sizes) process.stdout.write(`  ${s}\n`);
}

main();
